### PR TITLE
Added support for 'thekey', the '100% worth the money, macropad!

### PR DESCRIPTION
**Pull request by stautonico**
Yes I realize this is stupid, but this is just one step closer to supporting all QMK supported keyboards!

### CODE REVIEW

**Comment by yskoht** [comment]
@stautonico 

Thanks for the PR!

> `[thekey](https://github.com/andypiper/qmk_firmware/tree/so-thekey/keyboards/massdrop/thekey)`

keymapviz only supports keyboards from the `qmk/qmk_firmware` repository.

Will this keyboard be merged into the `qmk/qmk_firmware` repository?

**Comment by stautonico** [comment]
I don't think so, its a separate fork

**Comment by yskoht** [comment]
@stautonico 

Unfortunately, keymapviz only supports keyboards from the `qmk/qmk_firmware` repository.

Please send me another PR when `thekey` is merged into the `qmk/qmk_firmware` repository.

**Comment by stautonico** [comment]
Fair enough lol, this was kind of a meme anyway

**Pull request closed without merging**
